app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('', views.main_view, name='main'),
    path('members/', include('members.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
# coli/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('keygen/', views.generate_user_key, name='keygen'),
    path('pidgen/', views.create_pid, name='pidgen'),
    path('owners/', views.owners_view, name='owners'),
    path('transactions/', views.transaction_view, name='transactions'),
    path('browsers/', views.browse_view, name='browsers'),
]

app/members/forms.py
from bootstrap_datepicker_plus import DatePickerInput
from django import forms

SEX_CHOICES = (('male', 'Male'), ('female', 'Female'))
AUTHORITIES_CHOICES = (
    ('Owner', 'Pet Owner'),
    ('Vet', 'Veterinarian'),
    ('Comp', 'Company')
)


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )


class SignupForm(forms.Form):
    # Public_key는 회원가입에서 표기하지 않으므로 제외한다.
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    last_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    first_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )
    birthdate = forms.DateField(
        widget=DatePickerInput()
    )

    sex = forms.ChoiceField(
            choices=SEX_CHOICES,
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )
    authority = forms.ChoiceField(
            choices=AUTHORITIES_CHOICES,
    )


# Forms for PID
class CreatePIDForm(forms.Form):
    # Pet name
    pet_name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    # Pet Pics Upload button
    pet_image = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control-file btn',
                'style': 'background-color: #7f7b7c; color: white'
            }
        )
    )

    # Pet Birth date
    pet_birthdate = forms.DateField(
        widget=DatePickerInput()
    )

    # Pet Breed
    pet_breed = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    # Pet EntryNumber
    pet_entry = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    # Pet noseprint
    pet_noseprint = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control-file btn',
                'style': 'background-color: #7f7b7c; color: white'
            }
        )
    )

    # initial value from view(user.public_key)
    owner_key = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'readonly': True,
            }
        )
    )

    # Owner fingerprint
    owner_fingerprint = forms.ImageField(
        widget=forms.ClearableFileInput(
            attrs={
                'class': 'form-control-file btn',
                'style': 'background-color: #7f7b7c; color: white'
            }
        )
    )

    # Vet Key
    vet_key = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control'
            }
        )
    )

    # Owner Priavate key for signature
    owner_private_key = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control'
            }
        )
    )


    # Pet Parents
    # 펫의 부모를 확실히 링크시키기 위한 기능
    # 구현은 가능하나 복잡해질 가능성 우려하여 제외
    # pet_parents1 = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Parents Asset ID',
    #         }
    #     )
    # )
    # pet_parents2 = forms.CharField(
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Parents Asset ID',
    #         }
    #     )
    # )

# ------- 이하 Pet transaction은 CREATE 시에는 자동 생성--------
    # Pet Transactions
    # Create 단계에서는 최초 생성 트랜잭션으로 고정값
    # pet_transaction = ''

    # initial value from view(datetime.now)
    # date_created = forms.DateTimeField(
    #     widget=forms.HiddenInput()
    # )
    # initial value from view(datetime.now)
    # date_updated = forms.DateTimeField(
    #     widget=forms.HiddenInput()
    # )

app/members/views.py
import json

from bigchaindb_driver import BigchainDB
from bigchaindb_driver.crypto import generate_keypair
from django.contrib.auth import authenticate, login, logout
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from django.core.exceptions import ObjectDoesNotExist, ValidationError

from .forms import LoginForm, SignupForm, CreatePIDForm
from .models import User, LatestTransaction
import datetime


# Create your views here.
# Function of login process
def login_view(request):
    context = {
        'form': LoginForm()
    }

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main')

        else:
            context['error'] = '잘못된 ID 혹은 Password를 입력하셨습니다.'
    return render(request, 'members/login.html', context)


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('main')


# Function of sign up process
def signup_view(request):
    context = {
        'form': SignupForm(),
    }

    if request.method == 'POST':
        username = request.POST['username']
        password1 = request.POST['password1']
        password2 = request.POST['password2']
        last_name = request.POST['last_name']
        first_name = request.POST['first_name']
        birthdate = datetime.datetime.strptime(request.POST['birthdate'], '%m/%d/%Y').strftime('%Y-%m-%d')
        sex = request.POST['sex']
        email = request.POST['email']
        phone_number = request.POST['phone_number']
        authority = request.POST['authority']

        if User.objects.filter(username=username).exists():
            context['error'] = f'사용자명({username})은 이미 사용중입니다.'
        elif password1 != password2:
            context['error'] = f'비밀번호와 비밀번화 확인란의 값이 일치하지 않습니다.'
        else:
            try:
                user = User.objects.create_user(
                    username=username,
                    password=password1,
                    last_name=last_name,
                    first_name=first_name,
                    birthdate=birthdate,
                    sex=sex,
                    email=email,
                    phone_number=phone_number,
                    authority=authority
                )
                login(request, user)
                return redirect('main')
            except ValueError:
                # ValueError exception: datetime.date error
                context["error"] = f'회원가입에 실패했습니다(부정확한 생년월일 기입)'
            except ValidationError:
                # ValidationError exception: phone number validation error
                context["error"] = f'회원가입에 실패했습니다(잘못된 휴대전화 번호 기입)'
    return render(request, 'members/signup.html', context)


# User Key Set generate and download private_key
def generate_user_key(request):
    # Blockchain keypair 생성
    user_keypair = generate_keypair()
    user = request.user
    user.public_key = user_keypair.public_key
    user.save()

    # User private key download
    filename = 'private_key.txt'
    response = HttpResponse(
        user_keypair.private_key, content_type='text/plain'
    )
    response['Content-Disposition'] = f'attachment; filename={filename}'
    return response


# Pet Owner's Pet ID create
def create_pid(request):
    initial_data = {
        'pet_name': None,
        'pet_image': None,
        'pet_birthdate': None,
        'pet_breed': None,
        'pet_entry': None,
        'pet_noseprint': None,
        'owner_key': request.user.public_key,
        'owner_fingerprint': None,
        'vet': None,
        'private_key': None,
    }
    context = {
        'form': CreatePIDForm(initial=initial_data),
    }

    # if not POST(=GET), Render form itself
    # if POST, get Formdata and Make Transaction in Blockchain
    if request.method == 'POST':
        name = request.POST['pet_name']
        image = request.FILES['pet_image']
        birthdate = request.POST['pet_birthdate']
        breed = request.POST['pet_breed']
        entry = request.POST['pet_entry']
        noseprint = request.FILES['pet_noseprint']
        owner = request.POST['owner_key']
        fingerprint = request.FILES['owner_fingerprint']
        vet = request.POST['vet_key']
        private_key = request.POST['owner_private_key']

        # Local Default Storage에 저장 후 사용
        # 실제 서비스에서는 AWS S3를 사용 예정
        image_path = default_storage.save(
            f'{owner}/image.{image.content_type.split("/")[1]}',
            ContentFile(image.read())
        )

        noseprint_path = default_storage.save(
            f'{owner}/image.{noseprint.content_type.split("/")[1]}',
            ContentFile(noseprint.read())
        )

        fingerprint_path = default_storage.save(
            f'{owner}/image.{fingerprint.content_type.split("/")[1]}',
            ContentFile(fingerprint.read())
        )

        # 등록여부 검사 > 비문
        # 실제 서비스에서는 모든 비문의 메타데이터를 서버에서 관리할 것
        # On-chain에 저장하는 것이 아니라 효율을 위해 중앙화 서버에서 관리
        # 여기에서는 항상 Unique한 이미지가 들어오는 것으로 가정

        # PID Asset Data 정의
        PID_ASSET = {
            'data': {
                'pet_info': {
                    'pet_name': name,
                    'pet_image': image_path,
                    'pet_birth': birthdate,
                    'pet_breed': breed,
                    'pet_entry': entry,
                    'pet_noseprint': noseprint_path,
                    'owner': owner,
                    'owner_fingerprint': fingerprint_path
                },
                'pet_transactions': [
                    {
                        'transaction_num': 0,
                        'timestamp': json.dumps(datetime.datetime.now(), indent=4, sort_keys=True, default=str),
                        'agent': owner,
                        'transaction_type': 'CREATE',
                        # Vet 승인 시 Issue 확정
                        'content': f'PID Issue Application: {owner}',
                        # Vet 서명 이후 activated
                        'is_active': False
                    },
                ]
            }
        }

        # PID Metadata는 Vet이 승인한 이후에 생성

        # BigchainDB initailize
        db = BigchainDB('https://test.ipdb.io/')

        # prepare
        # 신청자 본인만 서명
        # Vet에게 소유권 제공 > Vet이 승인과 함께 다시 소유권 반환 > 발행 완료
        create_pid_prepare = db.transactions.prepare(
            operation='CREATE',
            signers=owner,
            # 승인 요청할 Vet
            recipients=vet,
            asset=PID_ASSET,
        )

        create_pid_fulfill = db.transactions.fulfill(
            create_pid_prepare,
            private_keys=private_key
        )

        create_pid_commit = db.transactions.send_commit(
            create_pid_fulfill
        )

        # 최신 트랜잭션 저장
        last_transaction = LatestTransaction.objects.create(
            user=request.user,
            asset_id=create_pid_fulfill['id'],
            entry_num=entry,
            is_active=False
        )
        last_transaction.save()

        return redirect('members:owners')
    return render(request, 'members/create_pid.html', context)


# Vet, Company User ID Create
# 시간이 없으니 스킵
def create_did(request):
    pass


# Owner 로그인 후 화면(PID 생성 진행 이후)
def owners_view(request):
    # 실제로는 여기서 해당 유저의 BigchainDB 트랜잭션을 찾아서 전달해야함
    # 시간이 없으니 그냥 보여주기용만 만들도록 함
    return render(request, 'members/owners.html')


# Browse 결과 화면
# 실제 검색 기능이 제외됨
def transaction_view(request):
    return render(request, 'members/transactions.html')


# Vet, Company Browser view
# 실제로는 더 많은 인증 과정 및 기능이 추가되어야 하나
# 양이 방대하여 시간이 너무 오래걸림
def browse_view(request):
    return render(request, 'members/browsers.html')


# Asset Data 정의
# PID
# PID_ASSET = {
#     'data': {
#         'pet_info': {
#             # PET의 NAME
#             'pet_name': 'NAME',

#             # Pet 이미지 URL(호스팅 API)
#             'pet_image': 'PET_IMAGE_URL',

#             # Pet 생일
#             'pet_birth': 'PET_BIRTHDAY',

#             # Pet 품종
#             'pet_breed': 'PET_BREED',

#             # Pet 순서(해당 유저가 보유한 Pet중 등록 순서)
#             'pet_entry': 'PET_ENTRY_NUM',
#             # 구현 제외
#             # 'pet_parents': 'PET_PARENTS_ASSET_ID'

#             # Pet 비문 > IMAGE DATA 사용
#             # 비문 및 지분 데이터 이미지 모두 실제 사용에 있어서는 Storage(S3)를 사용
#             'pet_noseprint': 'NOSEPRINT',

#             # Owner
#             'owner': 'PUBLIC_KEY',

#             # Owner 지문 > IMAGE DATA 사용
#             'owner_fingerprint': 'FINGERPRINT'
#         },
#         'pet_transactions': [
#             # 아래와 같은 Pet Transaction이 매 행위(transaction 발생)마다 쌓이게 된다.
#             {
#                 # pet_transactions에 한 element가 추가될 때마다 num이 ++된다
#                 # 전체 pet_transaction 수. 최초 생성시 생성에 대한 transaction 기록 = 1
#                 'transaction_num': 'num++',
#                 # 해당 transaction이 이루어진 시간, updated_datetime
#                 'timestamp': 'datetime.now',
#                 # 해당 transaction을 수행한 사람의 public key
#                 'agent': 'agent_public_key',
#                 # 해당 transaction이 어떠한 기능을 수행하기 위한 것인지 설명
#                 # CREATE : 최초 생성 / ADD : 의료 정보 추가
#                 # EDIT : PET_INFO 정보 수정 / RETRIEVE : 펫 정보 조회(By Company)
#                 # NOTE : 수의사는 자신이 치료한 동물 한정으로 자료 조회 가능,
#                 #        오너는 항상 자신의 펫만 자료 조회 가능
#                 'transaction_type': 'CREATE|ADD|EDIT|RETRIEVE',
#                 # 진료 및 조회 내용
#                 'content': 'TEXT INPUT'
#             },
#         ]
#     }
# }
#
# PID_METADATA = {
#     # Owner
#     'owner': 'OWNER_PUBLIC_KEY',
#     # ID Type (Pet or VET/COMPANY)
#     'ID_Type': 'PID|DID',
#     # trasaction number(same with transaction num in Asset)
#     'transaction_num': 'num',

app/templates/members/browsers.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
body {
  height: 100vh;
  position: relative;
  cursor: default;
}

::selection {
  background: transparent;
}

input::selection {
  color: #2d2d2d;
  background: rgba(#5EDF9E, 0.5);
}

a {
  text-decoration: none;
  color: #009dff;
}


.center {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}

#search {
  position: relative;
}

#search input, .ac {
line-height: 20px;
font-size: 20px;
font-weight: normal;
letter-spacing: 0em;
}

#search input {
    border: 0px;
    padding: 25px;
    padding-right: 100px;
    width: 450px;
    display: block;
    position: relative;
    transition: all 0.3s cubic-bezier(.55,0,.1,1);
}

#search input:focus {
      outline: none;
}
#search a.button:focus {
        right: -20px;
}

.ac {
    z-index: 1;
    position: absolute;
    left: 25px;
    top: 50%;
    transform: translateY(-50%);
    /* margin-top: 1px; */
    opacity: 0.3;
    pointer-events: none;
    transition: 0.3s cubic-bezier(.55,0,.1,1) all;
}

#search a.button {
    cursor: pointer;
    font-size: 16px;
    color: white;
    background: #5EDF9E;
    border: 0px;
    padding: 10px 30px;
    line-height: 20px;
    position: absolute;
    right: 0;
    top: 50%;
    transform: translate(25%, -50%);
    overflow: hidden;
    transition: all 0.3s cubic-bezier(.55,0,.1,1);
}


#search a.button:after,
#search a.button:before {
  position: absolute;
  background: #5EDF9E;
  color: white;
  width: 100%;
  height: 100%;
  top: 0;
  line-height: 40px;
  transition: 0.3s cubic-bezier(.55,0,.1,1) all;
  opacity: 0;
}

#search a.button:before {
  content: "Search";
  opacity: 1;
  left: 0;
}

#search a.button:after {
  content: "";
  left: 100%;
  font-size: 21px;
  line-height: 40px;
}

.aside {
  margin-bottom: 30px; z-index: 1}

#wrap {
  width: 800px;
  height: 600px;
  background: #c7c2c7;
  position: absolute;
    top: 15%;
    left: 30%;
  margin: 60px auto;
    opacity: 0.9;
}

{% endblock %}

{% block content %}
<!--네비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light sticky-top d-flex"
     style="background-color: #ded8d8; padding: 0 8px">
    <!--로고-->
    <a href="#" class="navbar-brand">
        <img src="{% static 'images/coli_logo.png' %}"
             width="50" height="50" alt="">
    </a>
    <!--메뉴 버튼-->
    <ul class="navbar-nav ml-md-auto">
        {%  if user.is_authenticated %}
            <li class="nav-item text-success font-weight-bold align-self-center mr-sm-2">
                    <b>Welcome! {{ user.get_short_name }}</b>
            </li>
            <li class="nav-item align-self-center mr-sm-2">
                <form action="{% url 'members:logout' %}" method="POST" style="margin: 0">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary">Logout</button>
                </form>
            </li>

        {% else %}
            <li class="nav-item align-self-center mr-sm-2">
                <a href="{% url 'members:login' %}" class="btn btn-outline-secondary">Login</a>
            </li>
            <li class="nav-item align-self-center mr-sm-2">
                <a href="{% url 'members:signup' %}" class="btn btn-outline-secondary">SignUp</a>
            </li>
        {% endif %}
        <li class="nav-item align-self-center mr-sm-2">
            <a href="#" class="btn btn-outline-secondary">Contacts</a>
        </li>
    </ul>
</nav>
<div class="jumbotron-fluid position-relative d-flex justify-content-center">
    <img src = "{% static 'images/animal_browser.png' %}" width="80%">
</div>

<div id="wrap">
  <div class="center">
    <div class="aside">
      <h1>Transaction Browser</h1>
      <p>Try typing in PUBKEY you want to retrieve:</p>
      <p>
        ex) 9t98CNNKo6Fp24EXUpy1WD5VoD3HZhuudYQtESwNnXdE<br/>
      </p>
    </div>

    <div id="search">
      <span class="ac ac-hidden"></span>
      <input type="text">
      <a class="button text-center" href="{% url 'members:transactions' %}" id="emoji">Search</a>
    </div>
  </div>
</div>

{% endblock %}

app/templates/members/owners.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
*{box-sizing: border-box;}
body, html {
    height: 100%; min-height: 100%;
    }
body {
   transform-style: preserve-3d;
   transform: perspective(800px);
}

#ID-carousel{
   width: 1000px;
   height: 500px;
   position:absolute;
   top: 50%; left: 50%;
   margin: -250px 0 0 -500px;
}

#card{
   animation: backAn 60s infinite;
   color:#fff;
   padding:30px;
   width:100%;
   height:100%;
{#   position:absolute;#}
   z-index:1;
   background:url(http://riccardotartaglia.it/img/deadpool/back.jpg) 100% bottom;
   box-shadow:
     0px 45px 100px rgba(0, 0, 0, .4),
     inset 0 0 0 1000px rgba(156,27,27,.6);
}
#card .text-block{position:relative;z-index:2;text-shadow: 0px 3px 10px rgba(0, 0, 0, .7)}
#card .text-block h1{font-family: 'Rubik', sans-serif; font-size:3em; margin:0; text-transform:uppercase; font-weight:700;}
#card .text-block h1 small{font-size:.4em;color:#ccc;position:relative;bottom:10px}
#card .text-block h3{margin:0;font-weight:700;}
#card .text-block p{font-weight:300; width:60%}
#card .text-block a.button{position:absolute; right:80px; bottom: -100px; transition: all .35s cubic-bezier(.37,.26,.35,1);border:4px solid #fff; padding:10px; background:transparent;font-family: 'Rubik', sans-serif;text-transform:uppercase; font-weight:700; cursor:pointer;}
#card .text-block a.button:hover{background:#B51D2A}


#card-container .pg{
    position:absolute;
    z-index: 2;
    height:450px; width:40%; right:40px;bottom:0px;z-index:2}
#card-container .pg > img{height:450px;}

button{color:#fff;}

@keyframes backAn {
  0%   { background-size:100% }
  50%   { background-size:250% }
  100%   { background-size:100% }
}
{% endblock %}

{% block content %}
<!--네비게이션 바-->
<nav class="navbar navbar-expand-lg navbar-light sticky-top d-flex"
     style="background-color: #ded8d8; padding: 0 8px">
    <!--로고-->
    <a href="#" class="navbar-brand">
        <img src="{% static 'images/coli_logo.png' %}"
             width="50" height="50" alt="">
    </a>
    <!--메뉴 버튼-->
    <ul class="navbar-nav ml-md-auto">
        {%  if user.is_authenticated %}
            <li class="nav-item text-success font-weight-bold align-self-center mr-sm-2">
                    <b>Welcome! {{ user.get_short_name }}</b>
            </li>
            <li class="nav-item align-self-center mr-sm-2">
                <form action="{% url 'members:logout' %}" method="POST" style="margin: 0">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary">Logout</button>
                </form>
            </li>

        {% else %}
            <li class="nav-item align-self-center mr-sm-2">
                <a href="{% url 'members:login' %}" class="btn btn-outline-secondary">Login</a>
            </li>
            <li class="nav-item align-self-center mr-sm-2">
                <a href="{% url 'members:signup' %}" class="btn btn-outline-secondary">SignUp</a>
            </li>
        {% endif %}
        <li class="nav-item align-self-center mr-sm-2">
            <a href="#" class="btn btn-outline-secondary">Contacts</a>
        </li>
    </ul>
</nav>

<div id="ID-carousel" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner rounded-lg">
        <div id="card-container" class="carousel-item active" data-offset="2">
           <div class="pg">
              <img src="/media/9t98CNNKo6Fp24EXUpy1WD5VoD3HZhuudYQtESwNnXdE/shiba.png">
           </div>
           <div id="card">
              <div class="text-block">
                 <h1>HARU <small> (2017.11.24)</small></h1>
                  <br>
                 <h3>3 Years Old Shiba Inu</h3>
                 <p>
                     <h3>Kim Do Hyang's Family</h3>
                     <br>
                    <small>Registration : 2019.11.31</small>
                  <br>
                      <small>
                      PUBKEY: {{ user.public_key }}
                      </small>
                  </p>
                  <br><br><br><br>
                 <a class="button text-decoration-none text-white" href="{% url 'members:transactions' %}">See More</a>
              </div>
           </div>
        </div>
        <div id="card-container" class="carousel-item" data-offset="2">
           <div class="pg">
              <img src="/media/9t98CNNKo6Fp24EXUpy1WD5VoD3HZhuudYQtESwNnXdE/pet.png">
           </div>
           <div id="card">
              <div class="text-block">
                 <h1>KITTY <small> (2018.01.15)</small></h1>
                  <br>
                 <h3>2 Years Old Pomeranian</h3>
                 <p>
                     <h3>Kim Do Hyang's Family</h3>
                     <br>
                    <small>Registration : 2019.11.31</small>
                  <br>
                      <small>
                      PUBKEY: {{ user.public_key }}
                      </small>
                  </p><br><br><br><br>
                 <a class="button text-decoration-none text-white" href="{% url 'members:transactions' %}">See More</a>
              </div>
           </div>
        </div>
    </div>

  <a class="carousel-control-prev" href="#ID-carousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#ID-carousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script>
$(document).ready(function() {
	$('#ID-carousel').carousel('cycle');
});
</script>
{% endblock %}

app/templates/members/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid col-lg-10 col-md-8 col-sm-6"
     style="border-radius: 1rem;
     border: 2px solid #7aa180;
     margin-top: 8rem; position:relative; padding: 5rem;">
    <img class="d-none d-lg-block d-xl-block"
            src="{% static 'images/sign_in_dog.png' %}"
         style="width: 30%; position: absolute; top: 30%; left: 10%" alt="">
    <div class="container-fluid align-middle">
        <h1 class="text-center col-lg-4 offset-lg-5 col-md-8 offset-md-2 col-sm-8 offset-sm-3">SIGNUP</h1>
        <small class="text-center text-danger font-weight-bold">
            {{ error }}
        </small>
        <form action="" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group col-lg-4 offset-lg-5 col-md-8 offset-md-2 col-sm-8 offset-sm-3">
                    <label for="{{ field.id_for_label }}">
                        {{ field.label }}
                    </label>
                    {{ field }}
                 </div>
            {% endfor %}
            <button class="btn btn-lg btn-primary btn-block col-lg-4 offset-lg-5 col-md-8 offset-md-2 col-sm-8 offset-sm-3"
                    type="submit">Sign In!</button>
        </form>
    </div>
</div>
{% endblock %}