app/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from . import views


urlpatterns = [
    path('', views.main_view, name='main'),
    path('members/', include('members.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

app/members/urls.py
# coli/members/urls.py
from django.urls import path

from . import views

app_name = 'members'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.signup_view, name='signup'),
    path('keygen/', views.generate_user_key, name='keygen'),
    path('pidgen/', views.create_pid, name='pidgen'),
    path('owners/', views.owners_view, name='owners'),
    path('transactions/', views.transaction_view, name='transactions'),
    path('browsers/', views.browse_view, name='browsers'),
]

app/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Normalize.css: 브라우저마다 다른 CSS기본 설정값들을 같게 맞춰줌 -->
	<link rel="stylesheet" href="{% static 'css/normalize.css' %}">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <style>
        body{
            background-color: #d6d0d0;
        }
        {% block css %}
        {% endblock %}
    </style>
    {% block extrahead %}
    {% endblock %}
    <title>COLI</title>
</head>
<body>
    <span class="wrap text-monospace">
        {% block content %}
        {% endblock %}
    </span>
</body>
</html>

app/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--네비게이션 바-->
		<nav class="navbar navbar-expand-lg navbar-light sticky-top d-flex"
             style="background-color: #ded8d8; padding: 0 8px">
            <!--로고-->
			<a href="#" class="navbar-brand">
                <img src="{% static 'images/coli_logo.png' %}"
                     width="50" height="50" alt="">
            </a>
			<!--메뉴 버튼-->
			<ul class="navbar-nav ml-md-auto">
	            {%  if user.is_authenticated %}
                    <li class="nav-item text-success font-weight-bold align-self-center mr-sm-2">
                            <b>Welcome! {{ user.get_short_name }}</b>
                    </li>
                    <li class="nav-item align-self-center mr-sm-2">
                        <form action="{% url 'members:logout' %}" method="POST" style="margin: 0">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-outline-secondary">Logout</button>
                        </form>
                    </li>

                {% else %}
                    <li class="nav-item align-self-center mr-sm-2">
                        <a href="{% url 'members:login' %}" class="btn btn-outline-secondary">Login</a>
                    </li>
                    <li class="nav-item align-self-center mr-sm-2">
                        <a href="{% url 'members:signup' %}" class="btn btn-outline-secondary">SignUp</a>
                    </li>
                {% endif %}
                <li class="nav-item align-self-center mr-sm-2">
					<a href="#" class="btn btn-outline-secondary">Contacts</a>
				</li>
			</ul>
		</nav>
{#----------#}
    {% if not user.is_authenticated %}
    <div class="jumbotron-fluid position-relative p-5">
        <img class="m-2" src = "{% static 'images/main_image.svg' %}" width="60%">
        <div class="container-fluid position-absolute text-right"
             style="top: 40%; right: 0; margin-right: 8rem">
            <p style="font-size: 2.5vw; font-weight: 600;">COLI:Pet DID Service</p>
            <p style="font-size: 1vw;">
                Protect your Adorable friend with COLI<br><br>
                It provides Identity of Pets as a distinct individual<br>
          and Easement for managing Petsonal information<br>
          by using Blockchain Technology
            </p>
        </div>
    </div>
    <hr>
    {#---------#}
    <div id = "content">
      <div class="container" style="margin-top: 8rem; margin-bottom: 8rem; text-align:center">
          <div class="row">
            <div class="col-4">
              <div class="card" style = "text-align:center; background-color: #cfc9c9; height: 400px"><text-align = center>
                <br>
                <img src="{% static 'images/dog.png' %}" width = "50%" height = "50%" >
                <div class="card-body" style="background-color: #cfc9c9">
                  <p class="card-text">Easy Registration <br> with their own Noseprint <br><br> "COLI will not hurt your Pet."</p><br>
                </div>
              </div>
            </div>
            <div class="col-4">
              <div class="card" style = "background-color: #cfc9c9; text-align:center; height: 400px"><text-align = center>
                <br>
                <img src="{% static 'images/check-list.png' %}" width = "50%" height = "50%"  >
                <div class="card-body" style="background-color: #cfc9c9">
                  <p class="card-text">Trusted Data Managing Platform for Petsonal Info <br><br> "Record Everything, <br> Search Easy, <br>Manage Data at-a-glance"</p>
                </div>
              </div>
            </div>
            <div class="col-4">
              <div class="card" style = "background-color: #cfc9c9; text-align:center; height:400px"><text-align = center>
                <br>
                <img src="{% static 'images/wanted.png' %}" width = "50%" height = "50%"  >
                <div class="card-body" style="background-color: #cfc9c9">
                  <p class="card-text">Find your Pets <br> with Image Recognition <br><br> "Lost friend, We'll find you"</p><br>
                </div>
              </div>
            </div>
          </div>
        </div>
        <hr>

    {#-------#}
     <div class="container" style = "text align :center; margin-bottom: 8rem; margin-top: 8rem">
        <text-align = center>
          <div class="row">
            <div class="col-4">

              <div class="card" style = "text-align:center;background-color: #cfc9c9; height: 300px; " ><text-align = center>
                <br>
                <div class = "card-head">
                <img src="{% static 'images/veterinarian.png' %}" width = "50%" height = "50%" >
                </div>
                <div class="card-body">

                  <p class="card-text">Visit  Vet near your home<br></p>
                    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search Vet in your town">
      <span class="input-group-btn">
         <button type="submit" class = "btn btn-outline-secondary" onClick="location.href='http://www.kvma.or.kr/find_shap'"><img src="{% static 'images/glass.png' %}" width = 20px height = 20px></button>
      </span>
    </div><br>

                </div>
              </div>
            </div>

            <div class="col-4">

              <div class="card" style = "text-align:center; height:300px;background-color: #cfc9c9; "><text-align = center>
                <br>
                <div class = "card-head">
                <img src="{% static 'images/vet.png' %}" width = "50%" height = "50%"  >
                </div>
                <div class="card-body">
                  <br>
                  <p class="card-text">Fill required Form <br> under the instruction of Vet</p>

                </div>
              </div>
            </div>

            <div class="col-4">

              <div class="card" style = "text-align:center;background-color: #cfc9c9; height: 300px"><text-align = center>
                <br>
                <div class = "card-head">
                <img src="{% static 'images/nose_print.png' %}" width = "100%" height = "50%"  >
                </div>
                <div class="card-body">

                  <p class="card-text"><br>Registrate Your Fingerprint <br>and Pet's Noseprint </p><br>

                </div>
              </div>
            </div>
            </div>
          </div>
        </div>
    </div>
{#-----------#}
    {% elif user.is_authenticated and not user.public_key %}
        <div class="jumbotron col-lg-6 offset-lg-3 col-md-8 offset-md-2" style="margin-top: 6%; background-color: #cfccca">
          <h1 class="display-5">Hello, {{ user.get_full_name }}!</h1>
          <p class="lead">
              You haven't made a <span style="color: #7aa180;">key</span> yet!<br>
              The key is required to store the DID in the Blockchain DB. <br>
              Please Click the button below to create and save your Key!
          </p>
          <hr class="my-4">
          <p class="text-danger font-weight-bold">
            Note: <br>
              You will only be able to download the key once, <br>
              and you will not be able to use the service if you lose it. <br>
              Also be careful not to spill it outside.
          </p>
          <a class="btn btn-primary btn-lg" href="{% url 'members:keygen' %}" role="button">Get your Keys!</a>
        {% if user.authority == 'Owner' %}
            <a class="btn btn-secondary btn-lg" href="{% url 'main' %}" role="button">Return to Home</a>
        {% endif %}
        {% if user.authority != 'Owner' %}
          <a class="btn btn-secondary btn-lg" href="{% url 'members:browsers' %}" role="button">Return to Home</a>
        {% endif %}
        </div>
{#----------------#}
    {% elif user.is_authenticated and user.public_key %}
        <!--Check user.public_key has an asset-->
        {% if not user.have_asset %}
            <div class="jumbotron col-lg-6 offset-lg-3 col-md-8 offset-md-2"
                 style="margin-top: 6%; background-color: #cfccca; border: solid 2px #8fd19e">
              <h1 class="display-5">Issue your New DID</h1>

              <!--for Pet Owner-->
              {% if user.authority == 'Owner' %}
                  <p class="lead">
                      You haven't made a <span style="color: #7aa180;">PID</span> yet!<br>
                      Please Visit a Vet near your home and Create an PID
                  </p>
                  <hr class="my-4">
                  <p class="text-info font-weight-bold">
                    Note: <br>
                      If you are registering a DID with your vet now,<br>
                      press the CREATE button below.
                  </p>
                  <a class="btn btn-success btn-lg offset-lg-10 offset-md-9"
                 href="{% url 'members:pidgen' %}" role="button">CREATE</a>

              <!--for Vet or Company-->
{#              {% else %}#}
{#                  <p class="lead">#}
{#                      You haven't made a <span style="color: #7aa180;">DID</span> yet!<br>#}
{#                      Please Fill out the following form and <br>#}
{#                      submit the required materials to issue a DID.#}
{#                  </p>#}
{#                  <hr class="my-4">#}
{#                  <p class="text-info font-weight-bold">#}
{#                    Note: <br>#}
{#                      Credentials for veterinarians and pet services companies are required.<br>#}
{#                      Press the CREATE button to continue.#}
{#                  </p>#}
{#                 <!--didgen url로 이동하도록-->#}
{#                  <a class="btn btn-success btn-lg offset-lg-10 offset-md-9"#}
{#                    href="{% url 'members:didgen' %}" role="button">CREATE</a>#}
              {% endif %}

            </div>
        {% endif %}
    {% endif %}
{% endblock %}